perlbrew_environment_variables:
    PERLBREW_HOME: "{{ perlbrew_home }}"
    PERLBREW_ROOT: "{{ perlbrew_root }}"
    PERLBREW_PERL: perl-system
    PERL5LIB: "{{ perlbrew_home }}/libs/perl-system@mediacloud/lib/perl5"
    PERL_MB_OPT: "--install_base {{ perlbrew_home }}/libs/perl-system@mediacloud"
    PATH: "{{ perlbrew_home }}/libs/perl-system@mediacloud/bin:{{ perlbrew_root }}/bin:{{ perlbrew_root }}/perls/perl-system/bin:{{ ansible_env.PATH }}"
    PERLBREW_MANPATH: "{{ perlbrew_home }}/libs/perl-system@mediacloud/man:{{ perlbrew_root }}/perls/perl-system/man"
    PERL_LOCAL_LIB_ROOT: "{{ perlbrew_home }}/libs/perl-system@mediacloud"
    PERLBREW_PATH: "{{ perlbrew_home }}/libs/perl-system@mediacloud/bin:{{ perlbrew_root }}/bin:{{ perlbrew_root }}/perls/perl-system/bin"
    PERLBREW_LIB: "mediacloud"
    PERL_MM_OPT: "INSTALL_BASE={{ perlbrew_home }}/libs/perl-system@mediacloud"

# CPAN mirror URL (CPAN, DarkPan or MiniCPAN)
perl_cpan_mirror: "https://s3.amazonaws.com/mediacloud-minicpan/minicpan-20170824/"

# Perl dependencies to install
#
# 1. Keep the list in alphabetical order
# 2. Write a short description for how this module is being used
perl_dependencies:
    - "Array::Compare"
    - "Carp::Always"
    - "Catalyst"
    - "Catalyst::Action::REST"
    - "Catalyst::Authentication::User::Hash"
    - "Catalyst::Controller::REST"
    - "Catalyst::Plugin::Authorization::ACL"
    - "Catalyst::Plugin::Authorization::Roles"
    - "Catalyst::Plugin::ConfigLoader"
    - "Catalyst::Plugin::StackTrace"
    - "Catalyst::Restarter"
    - "Catalyst::Runtime"
    - "CHI"
    - "Data::Dumper"
    - "Devel::Cover"
    - "Devel::Cover::Report::Coveralls"
    - "Devel::NYTProf"
    - "Domain::PublicSuffix"
    - "FCGI"
    - "FCGI::ProcManager"
    - "File::ReadBackwards"
    - "HTML::Entities"
    - "HTML::LinkExtractor"
    - "Inline"
    # Patched version of Inline::Python gets installed separately
    - "List::Compare"
    - "List::MoreUtils"
    - "Log::Log4perl"
    - "LWP::Protocol::https"
    - "LWP::UserAgent"
    - "Math::Prime::Util"
    - "MediaCloud::JobManager"
    - "Modern::Perl"
    - "Moose"
    - "namespace::autoclean"
    - "Net::AMQP::RabbitMQ"
    - "Net::IP"
    - "Parallel::Fork::BossWorkerAsync"
    - "Parallel::ForkManager"
    - "Parse::BooleanLogic"
    - "Perl::Tidy"
    - "Readonly"
    - "Readonly::XS"
    - "Regexp::Common"
    - "Regexp::Common::time"
    - "Scalar::List::Utils"
    - "Statistics::Basic"
    - "Sys::RunAlone"
    - "Template"
    - "Term::Prompt"
    - "Test::Differences"
    - "Test::NoWarnings"
    - "Text::CSV_XS"
    - "Text::Lorem::More"
    - "Text::Trim"
    - "Text::WordDiff"
    - "XML::FeedPP"
    - "XML::LibXML"
    - "XML::Simple"
