# Used for manually testing WAL-G

version: "3.7"

services:

    postgresql-server:
        image: gcr.io/mcback/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        environment:
            MC_WALG_ENABLE: "${MC_WALG_ENABLE}"
            MC_WALG_S3_ACCESS_KEY_ID: "${MC_WALG_S3_ACCESS_KEY_ID}"
            MC_WALG_S3_SECRET_ACCESS_KEY: "${MC_WALG_S3_SECRET_ACCESS_KEY}"
            MC_WALG_S3_REGION: "${MC_WALG_S3_REGION}"
            MC_WALG_S3_BUCKET_PREFIX: "${MC_WALG_S3_BUCKET_PREFIX}"
            # MC_WALG_S3_ENDPOINT: "${MC_WALG_S3_ENDPOINT}"
            # MC_WALG_S3_STORAGE_CLASS: "${MC_WALG_S3_STORAGE_CLASS}"
            # MC_WALG_S3_FORCE_PATH_STYLE: "${MC_WALG_S3_FORCE_PATH_STYLE}"
            # MC_WALG_S3_USE_LIST_OBJECTS_V1: "${MC_WALG_S3_USE_LIST_OBJECTS_V1}"
            # MC_WALG_S3_CA_CERT_BASE64: "${MC_WALG_S3_CA_CERT_BASE64}"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/postgresql-server/bin/
            - type: bind
              source: ./pgmigrate/
              target: /opt/postgresql-server/pgmigrate/
            - type: bind
              source: ./../postgresql-base/bin/
              target: /opt/postgresql-base/bin/
            - type: bind
              source: ./../postgresql-base/etc/postgresql/
              target: /etc/postgresql/
