- name: "Stop Apache service (MacOSX)"
  command: brew services stop apache2
  failed_when: false  # might not be started
  when: "ansible_distribution == 'MacOSX'"
  listen:
    - "Stop Apache notification"
  tags:
    - apache2-fcgi

- name: "Stop Apache service (Ubuntu / Debian)"
  service:
    name: apache2
    state: stopped
  when: "ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'"
  become: true
  become_user: root
  listen:
    - "Stop Apache notification"
  tags:
    - apache2-fcgi

- name: "Test if Apache service is stopped"
  command: "pgrep {% if ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' %}apache2{% else %}httpd{% endif %}"
  register: apache_status
  failed_when: "apache_status.stdout_lines | count > 0"
  changed_when: false
  listen:
    - "Stop Apache notification"
  tags:
    - apache2-fcgi

- name: "Start Apache service (MacOSX)"
  command: brew services start apache2
  failed_when: false  # might not be started
  when: "ansible_distribution == 'MacOSX'"
  listen:
    - "Start Apache notification"
  tags:
    - apache2-fcgi

- name: "Start Apache service (Ubuntu / Debian)"
  service:
    name: apache2
    state: started
  when: "ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'"
  become: true
  become_user: root
  listen:
    - "Start Apache notification"
  tags:
    - apache2-fcgi

- name: "Test if Apache service is started"
  command: "pgrep {% if ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' %}apache2{% else %}httpd{% endif %}"
  register: apache_status
  failed_when: "apache_status.stdout_lines | count == 0"
  changed_when: false
  listen:
    - "Start Apache notification"
  tags:
    - apache2-fcgi

- name: stop apache
  debug:
    msg: "stop apache"
  notify:
    - "Stop Apache notification"
  changed_when: true
  listen: stop apache
  tags:
    - apache2-fcgi

- name: stop apache right away
  meta: flush_handlers
  listen: stop apache
  tags:
    - apache2-fcgi

- name: start apache
  debug:
    msg: "start apache"
  notify:
    - "Start Apache notification"
  changed_when: true
  tags:
    - apache2-fcgi

- name: restart apache
  debug:
    msg: "restart apache"
  notify:
    - "Stop Apache notification"
    - "Start Apache notification"
  changed_when: true
  tags:
    - apache2-fcgi
