version: "3.7"

services:

    cliff-update-story-tags:
        image: dockermediacloud/cliff-update-story-tags:latest
        stop_signal: SIGKILL
        env_file: ./../common/common.env.dist
        environment:
            MC_CLIFF_VERSION_TAG: "cliff_clavin_v2.4.1"
            MC_CLIFF_GEONAMES_TAG_SET: "cliff_geonames"
            MC_CLIFF_ORGANIZATIONS_TAG_SET: "cliff_organizations"
            MC_CLIFF_PEOPLE_TAG_SET: "cliff_people"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/cliff-update-story-tags/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../cliff-base/src/
              target: /opt/mediacloud/src/cliff-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        stop_signal: SIGKILL
        expose:
            - 5432
