stages:

- stage: pull_build_push
  displayName: Pull, build, push images
  jobs:
  - job: pull_build_push
    displayName: Pull, build, push images
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/template-checkout.yml
      - template: .azure-pipelines/template-install-utils.yml
      - template: .azure-pipelines/template-install-docker.yml
      - template: .azure-pipelines/template-pull-images.yml
      - template: .azure-pipelines/template-build-images.yml
      - template: .azure-pipelines/template-push-images.yml

- stage: run_tests
  displayName: Run tests in chunks
  dependsOn: pull_build_push
  jobs:

  - job: run_tests_chunk_1
    displayName: Run tests in chunk 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/template-checkout.yml
      - template: .azure-pipelines/template-install-utils.yml
      - template: .azure-pipelines/template-install-docker.yml
      - template: .azure-pipelines/template-pull-images.yml
      - template: .azure-pipelines/template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: .azure-pipelines/template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_aa"

  - job: run_tests_chunk_2
    displayName: Run tests in chunk 2
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/template-checkout.yml
      - template: .azure-pipelines/template-install-utils.yml
      - template: .azure-pipelines/template-install-docker.yml
      - template: .azure-pipelines/template-pull-images.yml
      - template: .azure-pipelines/template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: .azure-pipelines/template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ab"

  - job: run_tests_chunk_3
    displayName: Run tests in chunk 3
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/template-checkout.yml
      - template: .azure-pipelines/template-install-utils.yml
      - template: .azure-pipelines/template-install-docker.yml
      - template: .azure-pipelines/template-pull-images.yml
      - template: .azure-pipelines/template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: .azure-pipelines/template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ac"

  - job: run_tests_chunk_4
    displayName: Run tests in chunk 4
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/template-checkout.yml
      - template: .azure-pipelines/template-install-utils.yml
      - template: .azure-pipelines/template-install-docker.yml
      - template: .azure-pipelines/template-pull-images.yml
      - template: .azure-pipelines/template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: .azure-pipelines/template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ad"

  - job: run_tests_chunk_5
    displayName: Run tests in chunk 5
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/template-checkout.yml
      - template: .azure-pipelines/template-install-utils.yml
      - template: .azure-pipelines/template-install-docker.yml
      - template: .azure-pipelines/template-pull-images.yml
      - template: .azure-pipelines/template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: .azure-pipelines/template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ae"
