# Python dependencies to install
#
# 1. Keep the list in alphabetical order
# 2. Write a short description for how this module is being used
python_dependencies:

    # Datetime parsing
    - { name: "arrow", version: "0.10.0" }

    # Deployments
    - { name: "ansible", version: "2.3.2.0" }

    # HTML parsing
    - { name: "beautifulsoup4", version: "4.6.0" }

    # Unit test coverage
    - { name: "coverage", version: "4.4.1" }

    # Stemming Hausa words
    - { name: "hausastemmer", version: "1.0" }

    # Chinese language tokenizer, stemmer, etc.
    - { name: "jieba", version: "0.38" }

    # Parsing email templates
    - { name: "Jinja2", version: "2.9.6" }

    # Japanese language tokenizer, stemmer, etc.
    - { name: "mecab-python3", version: "0.7" }

    # network analysis, used for graph layout
    - { name: "networkx", version: "1.11" }

    # Natural language processing, e.g. tokenization
    - { name: "nltk", version: "3.2.4" }

    # Unit tests
    - { name: "pytest", version: "3.2.2" }

    # numerical processing, required by ForceAtlas2
    - { name: "numpy", version: "1.13.1" }

    # Finding out which Readability version we're using
    - { name: "pip", version: "9.0.1" }

    # PostgreSQL
    - { name: "psycopg2", version: "2.7.3" }

    # Configuration file
    - { name: "pyyaml", version: "3.12" }

    # Date parsing
    - { name: "python-dateutil", version: "2.6.1" }

    # Extracting text from stories
    - { name: "readability-lxml", version: "0.6.2" }

    # Making HTTP requests
    - { name: "requests", version: "2.18.4" }

    # math package for forceatlas implementation
    - { name: "scipy", version: "0.19.1" }

    # Normalizing URLs
    - { name: "url_normalize", version: "1.3.3" }
