version: "3.7"

services:

    # Service to use for testing the mail service
    #
    # Usage:
    #
    #     host$ ./dev/run.py mail-postfix-server bash
    #     container$ sendmail "your@email.com"
    #
    mail-postfix-server:
        image: dockermediacloud/common:latest
        stop_signal: SIGKILL
        depends_on:
            - mail-postfix-server-actual

    # Actual mail server, operating under "mail-postfix-server" alias
    mail-postfix-server-actual:
        image: dockermediacloud/mail-postfix-server:latest
        stop_signal: SIGKILL
        # "docker exec" into a container and run Postfix manually (/postfix.sh):
        command: sleep infinity
        # To be able to set /proc/sys/kernel/yama/ptrace_scope:
        privileged: true
        environment:
            MC_MAIL_POSTFIX_FQDN: "mail.testmediacloud.ml"
        depends_on:
            - mail-opendkim-server
        networks:
            default:
                aliases:
                    - mail-postfix-server

    mail-opendkim-server:
        image: dockermediacloud/mail-opendkim-server:latest
        environment:
            MC_MAIL_OPENDKIM_DOMAIN: "testmediacloud.ml"
            MC_MAIL_OPENDKIM_HOSTNAME: "mail"
        expose:
            - "12301"
        volumes:
            - type: bind
              source: ./../mail-opendkim-server/etc/opendkim.conf
              target: /etc/opendkim.conf
            - type: bind
              source: ./../mail-opendkim-server/etc/opendkim/
              target: /etc/opendkim/

networks:
    default:
        attachable: true
        ipam:
            driver: default
            config:
                # Use same subnet as in production
                - subnet: "10.1.0.0/16"
