---

# Python version to install and use
python_version: 3.7

# Repository URL
git_repo_url: https://github.com/berkmancenter/mediacloud.git

# Branch to clone
git_clone_branch: release

# Perlbrew variables
perlbrew_root: "{{ mediacloud_home }}/perl5/perlbrew/"
perlbrew_home: "{{ mediacloud_home }}/.perlbrew/"

# Serve Media Cloud webapp via SSL
apache2_ssl_enabled: false

# (required if SSL is enabled) SSL certificate path (must exist beforehand)
apache2_ssl_cert_path: /etc/ssl/certs/ssl-cert-snakeoil.pem

# (required if SSL is enabled) SSL private key path (must exist beforehand)
apache2_ssl_cert_key_path: /etc/ssl/private/ssl-cert-snakeoil.key

# ServerName (e.g. core.mediacloud.org)
apache2_server_name: "{{ ansible_hostname }}"

# (optional) SSL intermediate certificate path (must exist beforehand)
# apache2_ssl_cert_chain_path: /etc/ssl/certs/mediacloud_interm.crt
