---

- name: Include variables
  include_vars: ../vars/main-{{ ansible_distribution }}.yml
  tags:
    - perl-dependencies

- name: Copy Perlbrew environment variables
  set_fact:
    perlbrew_environment_variables_copy: "{{ perlbrew_environment_variables }}"
  tags:
    - perl-dependencies

- name: Update Perlbrew environment variables
  set_fact:
    perlbrew_environment_variables_copy: "{{ perlbrew_environment_variables_copy | combine({ item.name: item.value }) }}"
  with_items:

    # Use correct Python with Inline::Python
    - { name: "INLINE_PYTHON_EXECUTABLE", value: "{{ mediacloud_home }}/.virtualenvs/mediacloud/bin/python{{ python_version }}" }

    # OS X no longer provides OpenSSL headers and Net::AMQP::RabbitMQ doesn't care
    # about OPENSSL_PREFIX so we need to set CCFLAGS and install the module
    # separately.
    #
    # Additionally, we reset LD to just "cc" in order to remove
    # MACOSX_DEPLOYMENT_TARGET parameter.
    - { name: "CCFLAGS", value: "-I{{ openssl_prefix }}/include" }
    - { name: "LDFLAGS", value: "-L{{ openssl_prefix }}/lib" }
    - { name: "LD", value: "env cc" }

  tags:
    - perl-dependencies

- name: Install Inline module
  cpanm:
    name: "Inline"
    notest: true
  environment: "{{ perlbrew_environment_variables_copy }}"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - perl-dependencies

- name: Install Inline::Python variant which die()s with tracebacks (stack traces)
  command: "cpanm -v https://github.com/berkmancenter/mediacloud-inline-python-pm.git@v0.56-mediacloud"
  # No "args/creates" because installing from Git tree, so not sure how to
  # check which particular tag got installed
  environment: "{{ perlbrew_environment_variables_copy }}"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - perl-dependencies

- name: Install Media Cloud Perl dependencies with Cpanm
  cpanm:
    name: "{{ item }}"
    notest: true # `carton install` didn't run tests either
    mirror: "{{ perl_cpan_mirror }}"
    mirror_only: true
  with_items: "{{ perl_dependencies }}"
  environment: "{{ perlbrew_environment_variables_copy }}"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - perl-dependencies
