---

- include_vars: ../vars/main-{{ ansible_distribution }}.yml
  tags:
    - perl-dependencies

- name: Copy Perlbrew environment variables
  set_fact:
    perlbrew_environment_variables_copy: "{{ perlbrew_environment_variables }}"
  tags:
    - perl-dependencies

- name: Update Perlbrew environment variables
  set_fact:
    perlbrew_environment_variables_copy: "{{ perlbrew_environment_variables_copy | combine({ item.name: item.value }) }}"
  with_items:

    # Use correct Python with Inline::Python
    - { name: "INLINE_PYTHON_EXECUTABLE", value: "{{ ansible_env.HOME }}/.virtualenvs/mediacloud/bin/python{{ python_version }}" }

    # OS X no longer provides OpenSSL headers and Net::AMQP::RabbitMQ doesn't care
    # about OPENSSL_PREFIX so we need to set CCFLAGS and install the module
    # separately.
    #
    # Additionally, we reset LD to just "cc" in order to remove
    # MACOSX_DEPLOYMENT_TARGET parameter.
    - { name: "CCFLAGS", value: "-I{{ openssl_prefix }}/include" }
    - { name: "LDFLAGS", value: "-L{{ openssl_prefix }}/lib" }
    - { name: "LD", value: "env cc" }

  tags:
    - perl-dependencies

- name: Install Media Cloud Perl dependencies with Cpanm
  cpanm:
    name: "{{ item.name }}"
    version: "{{ item.min_version }}"
    notest: true # `carton install` didn't run tests either
    mirror: "{{ perl_darkpan_url }}"
    mirror_only: true
  with_items: "{{ perl_dependencies }}"
  environment: "{{ perlbrew_environment_variables_copy }}"
  tags:
    - perl-dependencies
