# For whatever reason having handlers in separate per-OS files doesn't work in Ansible 2.4

- name: Restart PostgreSQL service (MacOSX)
  command: "brew services restart postgresql"
  listen: "Restart PostgreSQL (MacOSX)"
  tags:
    - postgresql-server

- name: "Test if PostgreSQL is running after restart (MacOSX)"
  command: "pgrep postgres"
  register: postgresql_status
  failed_when: "postgresql_status.stdout_lines | count == 0"
  changed_when: false
  listen: "Restart PostgreSQL (MacOSX)"
  tags:
    - postgresql-server

- name: "Restart PostgreSQL service (Ubuntu)"
  service:
    name: postgresql
    state: restarted
  become: true
  become_user: root
  listen: "Restart PostgreSQL (Ubuntu)"
  tags:
    - postgresql-server

- name: "Test if PostgreSQL is running after restart (Ubuntu)"
  command: "pgrep postgres"
  register: postgresql_status
  failed_when: "postgresql_status.stdout_lines | count == 0"
  changed_when: false
  listen: "Restart PostgreSQL (Ubuntu)"
  tags:
    - postgresql-server

- name: "Restart PostgreSQL service (Debian)"
  service:
    name: postgresql
    state: restarted
  become: true
  become_user: root
  listen: "Restart PostgreSQL (Debian)"
  tags:
    - postgresql-server

- name: "Test if PostgreSQL is running after restart (Debian)"
  command: "pgrep postgres"
  register: postgresql_status
  failed_when: "postgresql_status.stdout_lines | count == 0"
  changed_when: false
  listen: "Restart PostgreSQL (Debian)"
  tags:
    - postgresql-server

- name: restart postgresql
  debug:
    msg: "restart postgresql"
  notify:
    - "Restart PostgreSQL ({{ ansible_distribution }})"
  changed_when: true
  tags:
    - postgresql-server
