#
# Doesn't work with dev/run.sh; for development, start it as such:
#
#     cd apps/solr-shard/
#     docker-compose \
#         --project-name mc-solr-shard-bash \
#         --file docker-compose.tests.yml \
#         --compatibility up \
#         --renew-anon-volumes \
#         --force-recreate
#

version: "3.7"

# Base service for Solr shard
x-solr-shard_base:   &solr-shard_base
    image: dockermediacloud/solr-shard:latest
    init: true
    stop_signal: SIGKILL
    environment:
        MC_SOLR_SHARD_COUNT: "4"
    networks:
        - default
    ports:
        # Map to random port on the host for them not to clash
        - "8983"
    depends_on:
        - solr-zookeeper
    networks:
        - default

services:

    solr-shard_01:
        <<: *solr-shard_base
        volumes:
            - vol_solr_shard_data_01:/var/lib/solr/
            - type: bind
              source: ./bin/solr-shard.sh
              target: /solr-shard.sh

    solr-shard_02:
        <<: *solr-shard_base
        volumes:
            - vol_solr_shard_data_02:/var/lib/solr/
            - type: bind
              source: ./bin/solr-shard.sh
              target: /solr-shard.sh

    solr-shard_03:
        <<: *solr-shard_base
        volumes:
            - vol_solr_shard_data_03:/var/lib/solr/
            - type: bind
              source: ./bin/solr-shard.sh
              target: /solr-shard.sh

    solr-shard_04:
        <<: *solr-shard_base
        volumes:
            - vol_solr_shard_data_04:/var/lib/solr/
            - type: bind
              source: ./bin/solr-shard.sh
              target: /solr-shard.sh

    solr-zookeeper:
        image: dockermediacloud/solr-zookeeper:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888
        networks:
            - default
        volumes:
            - type: bind
              source: ./../solr-zookeeper/conf/
              target: /opt/zookeeper/conf/
            - type: bind
              source: ./../solr-zookeeper/bin/zookeeper.sh
              target: /zookeeper.sh

networks:
    default:

volumes:
    vol_solr_shard_data_01: {}
    vol_solr_shard_data_02: {}
    vol_solr_shard_data_03: {}
    vol_solr_shard_data_04: {}
