version: "3.7"

services:

    munin-node:
        image: dockermediacloud/munin-node:latest
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./plugins/
              target: /etc/munin/plugins/
        depends_on:
            # Monitors a bunch of stuff on PostgreSQL
            - postgresql-pgbouncer
            # Monitors stuff on Solr too
            - solr-shard

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        ports:
            # Publish port to host for debugging and PyCharm access
            - "127.0.0.1:6432:6432"
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    solr-shard:
        image: dockermediacloud/solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - solr-zookeeper

    solr-zookeeper:
        image: dockermediacloud/solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888
