crontab_mailto:
  - hroberts@cyber.law.harvard.edu
  - lvaliukas@cyber.law.harvard.edu

crontab_import_solr_data_nice: 15
crontab_import_solr_data_jobs: 8
crontab_import_solr_data_log_path: "{{ mediacloud_root }}/data/logs/import_solr_data.log"

crontab_rotate_supervisor_logs_log_path: "{{ mediacloud_root }}/data/logs/rotate_supervisor_logs.log"

crontab_rotate_http_request_log_log_path: "{{ mediacloud_root }}/data/logs/rotate_http_request_log.log"

crontab_rescrape_due_media_log_path: "{{ mediacloud_root }}/data/logs/rescrape_media.log"

crontab_rss_dump_path: "{{ mediacloud_root }}/data/rss_dumps"
