---

# We connect to PgBouncer often, so it might run out of available connections
# without TIME_WAIT socket reuse (http://dba.stackexchange.com/a/59709)
- name: Add net.ipv4.tcp_tw_reuse=1 to sysctl's configuration
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present
    sysctl_file: "{{ sysctl_conf_path }}"
    sysctl_set: yes
    reload: yes
  become: true
  tags:
    - kernel-parameters
