---

- name: Install RabbitMQ
  tags:
    - system-packages
  block:

    - name: Add Erlang Solutions GPG key
      apt_key:
        url: "https://packages.erlang-solutions.com/{{ ansible_distribution | lower }}/erlang_solutions.asc"
        state: present
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Add RabbitMQ PackageCloud GPG key
      apt_key:
        url: "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
        state: present
      become: true
      become_user: root
      tags:
        - system-packages

    # RabbitMQ > 3.7 requires newer Erlang than is provided by Ubuntu 16.04 / Debian
    - name: Add Erlang Solutions APT repository
      apt_repository:
        repo: "deb https://packages.erlang-solutions.com/{{ ansible_distribution | lower }} {{ ansible_lsb.codename | lower }} contrib"
        state: present
        filename: "erlang-solutions"
        update_cache: yes
      become: true
      become_user: root
      tags:
        - system-packages

    # Bintray APT repository is no longer supported
    - name: Remove obsolete Bintray RabbitMQ repository
      apt_repository:
        repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_lsb.codename | lower }} main"
        state: absent
        filename: "bintray-rabbitmq"
        update_cache: yes
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Remove empty Bintray RabbitMQ repository sources file
      file:
        path: /etc/apt/sources.list.d/bintray-rabbitmq.list
        state: absent
      become: true
      become_user: root
      tags:
        - system-packages        

    - name: Add RabbitMQ APT repository
      apt_repository:
        repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/{{ ansible_distribution | lower }}/ {{ ansible_lsb.codename | lower }} main"
        state: present
        filename: "packagecloud-rabbitmq"
        update_cache: yes
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Install Erlang
      apt:
        name: "{{ item }}={{ erlang_apt_package_version }}"
        state: present
        install_recommends: false

        # Workaround to enable --allow-downgrades
        # (systems that are being deployed to might have a newer version(s) installed)
        force: true
        force_apt_get: true

      with_items: "{{ erlang_apt_packages }}"
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Install RabbitMQ
      apt:
        name: "rabbitmq-server={{ rabbitmq_apt_package_version }}"
        state: present
        install_recommends: false
        
        # Workaround to enable --allow-downgrades
        # (systems that are being deployed to might have a newer version(s) installed)
        force: true
        force_apt_get: true

      become: true
      become_user: root
      tags:
        - system-packages

    - name: Stop and disable system RabbitMQ
      service:
        name: rabbitmq-server
        enabled: no
        state: stopped
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Prevent Erlang by being upgraded by APT
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items: "{{ erlang_apt_packages }}"
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Prevent RabbitMQ by being upgraded by APT
      dpkg_selections:
        name: rabbitmq-server
        selection: hold
      become: true
      become_user: root
      tags:
        - system-packages

- name: Install mecab-ipadic-neologd
  tags:
    - system-packages
  block:

    # apt_key doesn't work for whatever reason
    - name: Add Bintray.com GPG key
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
      changed_when: false
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Add mecab-ipadic-neologd APT repository
      apt_repository:
        repo: "deb https://dl.bintray.com/mediacloud/mecab-ipadic-neologd-deb stable main"
        state: present
        filename: "bintray-mediacloud-mecab-ipadic-neologd"
        update_cache: yes
      become: true
      become_user: root
      tags:
        - system-packages

    - name: Install mecab-ipadic-neologd
      apt:
        name: "{{item}}"
        state: present
        install_recommends: false
      with_items:
        - mecab
        - mecab-ipadic-neologd
      become: true
      become_user: root
      tags:
        - system-packages

# Ubuntu 16.04 doesn't distribute Python 3.7
- name: Add Python deadsnakes repository
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
  become: true
  become_user: root
  tags:
    - system-packages

- name: Install system packages
  apt:
    name: "{{item}}"
    state: present
    install_recommends: false
  with_items:
    - curl
    - build-essential
    - ca-certificates
    - cpanminus
    - curl
    - expat
    - g++
    - gawk
    - gcc
    - graphviz
    - graphviz-dev
    - hunspell
    - libexpat1-dev
    - libhunspell-dev
    - libmecab-dev
    - libgraphviz-dev
    - libre2-dev
    - libtidy-dev
    - libxml2-dev
    - libxml2-dev
    - libxslt1-dbg
    - libxslt1-dev
    - libxslt1.1
    - libyaml-dev
    - libssl-dev  # OpenSSL headers
    - logrotate
    - make
    - netcat
    - openjdk-8-jdk
    - pkg-config
    - python-pip
    - python2.7
    - python2.7-dev
    - unzip
  become: true
  become_user: root
  tags:
    - system-packages

# APT's version is too old
- name: Remove obsolete Supervisor
  apt:
    name: supervisor
    state: absent
    install_recommends: false
  become: true
  become_user: root
  tags:
    - system-packages

- name: Use Java 8 by default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  become: true
  become_user: root
  tags:
    - system-packages
