steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.7"
    addToPath: true

- script: pip install -U pip setuptools wheel
  displayName: Upgrade Pip / setuptools

- script: sudo apt-get -y update
  displayName: Update APT listing

- script: sudo apt-get -y install parallel
  displayName: Install parallels

# Install PyYAML for docker-compose.yml validation
- script: pip install PyYAML
  displayName: Install PyYAML
